import { uiEnglish } from './ui.ts';
import { aboutCopy } from '../data/about.ts';
import { projectDetails, researchFields } from '../data/english.ts';
import { paperEnglish } from '../data/papers.ts';

export const baseContent = {
  ui: uiEnglish,
  about: aboutCopy.en,
  projectDetails,
  fields: researchFields,
  papers: paperEnglish,
  home: {
    title: 'Astrmira · Research, systems, and lasting curiosity', description: 'Astrmira studies foundational questions in data and intelligence, then builds open systems that carry research into the real world.',
    kicker: 'A wonderful star', subtitle: 'Seek the unknown. Build beyond the horizon.', supporting: 'From first principles to real-world intelligence.', introduction: ['We study foundational questions in data, computation, and intelligence,', 'then turn rigorous ideas into systems people can use.'], explore: 'Explore our research', discover: 'Discover projects',
    researchLabel: 'Our research', researchHeading: ['From one question,', 'toward new understanding.'], researchNote: 'We frame questions, build methods, and test ideas through derivation and experiment, letting each finding become the beginning of the next inquiry.', papersLabel: 'Research, in the open', papersHeading: ['Keep asking', 'into the unknown.'], papersNote: 'From foundational problems to new findings across different fields, this is where we record our papers and research progress.', allResearch: 'All research',
    practiceLabel: 'Our practice', practiceHeading: ['Exploration goes', 'beyond the paper.'], practiceNote: 'Foundational research expands what is possible. Building systems lets real problems answer back.', projectsLabel: 'Ideas, made tangible', projectsHeading: ['Build research', 'into reality.'], projectsNote: 'From data foundations and intelligent companions to sustained execution for complex work.',
    nameLabel: 'A note on our name', nameHeading: ['A wonderful star.', 'A lasting curiosity.'], nameMotto: 'Stars change. Curiosity continues.', nameStory: 'Astr evokes the distant sky; Mira is a real variable star; Mirage is an imagined horizon still to be reached. These images come together in our Chinese name, 幻梦星芒.', nameMeaning: 'Mira changes in brightness and leaves a long ultraviolet tail. It reminds us to preserve imagination around the unknown and leave a trail that others can continue.', nameSource: 'Name inspiration · NASA',
    ctaLabel: 'Let’s ask the next question', ctaHeading: ['The next question worth studying', 'may come from you.'], ctaText: 'Databases and intelligent systems · Research collaboration · University partnerships', ctaNote: 'Begin a meaningful collaboration with one real problem.', cta: 'Start a conversation',
  },
  cards: {
    trivium: { label: 'Systems', accessible: 'Explore the TriviumDB embedded database', description: 'An AI-native embedded database in Rust that unifies vectors, property graphs, and documents for agent memory and local knowledge.', tags: 'Vector · Graph · Document' },
    infos: { label: 'Intelligence', accessible: 'Explore the infOS AI companion runtime', description: 'An open-source runtime for AI companions, connecting long-term memory, context, and tools while powering persistent conversation and desktop interaction.', tags: 'Memory · Context · Tools' },
    piarium: { label: 'Agent harness', accessible: 'Explore the Piarium agent harness', description: 'A complete agent harness for complex engineering work, spanning code retrieval, context and memory, multi-agent coordination, and verifiable delivery.', tags: 'Context · Execution · Verification' },
  },
  projectPage: { title: 'Projects · Open-source systems — Astrmira', description: 'Explore Astrmira projects: TriviumDB, infOS, and the Piarium agent harness.', label: 'Projects / Open source', heading: ['Ideas,', 'made tangible.'], introduction: 'From the data core in TriviumDB and the companion runtime in infOS to sustained execution in Piarium, we build research into systems people can use.', noteHeading: 'Research and products move in both directions.', note: 'Research gives systems new methods. Real use gives research new questions.' },
  researchPage: { title: 'Research and publications — Astrmira', description: 'Read Astrmira papers and explore the questions, methods, and findings behind our research.', label: 'Research / Publications', heading: ['Questions.', 'Evidence. Progress.'], introduction: 'Our research begins with questions worth asking, then builds methods and evidence across different fields. This page brings together papers, current directions, and the next questions opened by each result.', fieldsLabel: 'Explore the directions', fieldsHeading: 'Follow a question into its field.', fieldsNote: 'Browse the foundations that connect our work in data systems, retrieval, representation, efficient intelligence, and mathematics.', question: 'Have a question worth pursuing together?', contact: 'Talk with us' },
  fieldPage: { label: 'Research field', unfolding: 'an unfolding question.', direction: 'Research direction', questions: 'Open questions', begin: 'Begin with the question.', approach: 'We approach this field by making assumptions explicit, connecting methods to measurable behavior, and allowing experiments and systems to refine the question itself.', conversation: 'Start a research conversation' },
  partnerships: { title: 'Research partnerships', description: 'Work with Astrmira on shared scientific questions across data systems, efficient intelligence, and mathematics.', heading: ['Let a good question', 'meet shared curiosity.'], introduction: 'Research and university partnerships are a core direction. We connect our work in databases, retrieval, quantization, post-training, and mathematics to scientific questions that benefit from different kinds of experience.', label: 'Joint research', planning: 'Research planning', prototypes: 'Prototypes and evaluation', sections: [{ title: 'Begin with the question itself.', text: 'Questions worth sustained study often need theoretical insight, experimental method, and systems experience together. A collaboration begins with the problem rather than a predetermined technical answer.' }, { title: 'Ways to work together.', text: 'Joint problem selection, research prototypes, experimental evaluation, technical exchange, and paths toward practical use. Scope, ownership, and disclosure are agreed explicitly for each collaboration.' }, { title: 'How to begin.', text: 'Bring a question, a research plan, or a cross-disciplinary challenge. We first discuss the goal, existing foundation, and what can be shared, then design an appropriate path.' }], discuss: 'Discuss this direction' },
  collaborate: { title: 'Collaborate with Astrmira', description: 'Begin a research or engineering collaboration with Astrmira.', label: 'Collaborate / Begin with a question', heading: ['The next question', 'starts with you.'], introduction: 'Bring a real scenario, an open question, or a research plan. We begin by making the problem clear, then decide how to move forward together.', sideTitle: 'Let us begin with the problem.', sideNote: 'Describe the context, existing foundation, and desired outcome to generate a concise collaboration brief.', aspects: ['Databases and retrieval', 'Agent applications', 'Research and universities'] },
};
