export const uiEnglish = {
  nav: { home: 'Home', projects: 'Projects', research: 'Research', about: 'About', collaborate: 'Work with us', contact: 'Contact', menu: 'Menu', navigation: 'Main navigation', language: 'Language', currentLanguage: 'Choose language, current: {language}', homeLabel: 'Astrmira home' },
  footer: { motto: 'Research-driven. Possibility-bound.', back: 'Back to top', star: 'A wonderful star' },
  motion: { replay: 'Replay', replayLabel: 'Replay the moving star and particle typography', pause: 'Pause motion', enable: 'Enable motion', reduced: 'Reduced motion', scroll: 'Scroll to discover' },
  toc: { title: 'On this page', overview: 'Overview' },
  carousel: { label: 'Research papers, horizontally scrollable', note: 'Papers · Findings · Progress', browse: 'Browse', previous: 'View previous papers', next: 'View next papers', separator: '; ' },
  common: { openSource: 'Open source', license: 'License', github: 'View on GitHub', documentation: 'Read the documentation', releases: 'View releases', discuss: 'Discuss an application or collaboration', readResearch: 'Read our research', astronomicalRecord: 'Astronomical record', astronomySource: 'Astronomical source', lastingCuriosity: 'A lasting curiosity', beginQuestion: 'Begin with a question', newWindow: 'opens in a new window' },
  projects: { all: 'All projects', data: 'Data systems', agents: 'Agents', harness: 'Agent harness', filter: 'Filter projects', count: '{count} projects', countOne: '{count} project' },
  research: { all: 'All papers', vectors: 'Vector search', llms: 'LLM quantization', theory: 'Representation and theory', filter: 'Filter papers', label: 'Research papers', search: 'Search papers, authors, or keywords…', empty: 'No matching paper was found. Try another keyword or research direction.', count: '{count} papers', countOne: '{count} paper', browseFields: 'Browse research fields', arxivLabel: 'Read {title} on arXiv (new window)' },
  paper: { details: 'Paper details', authors: 'Authors', submitted: 'First submitted', revised: 'Latest revision', version: 'Public version', arxiv: 'Read on arXiv', pdf: 'Open versioned PDF', readCite: 'Read and cite', continue: 'Continue with the original paper.', original: 'The complete derivations, experimental setup, and results are available in the public manuscript.', versions: 'Abstract and version history', fullPdf: 'Full paper PDF', related: 'Related papers' },
  form: {
    name: 'Your name (optional)', namePlaceholder: 'Name', organization: 'Organization or team (optional)', organizationPlaceholder: 'University, lab, or company', area: 'Collaboration area', areas: ['Joint research', 'Databases and retrieval systems', 'Agent platforms and applications', 'Another question worth discussing'], problem: 'What problem would you like to solve together? *', placeholder: 'Context, current foundation, and the outcome you hope to reach…', submit: 'Generate collaboration brief', note: 'You can copy or download it. Nothing is sent automatically.', result: 'Your collaboration brief', copy: 'Copy text', download: 'Save as .txt', generated: 'The brief was generated locally and has not been sent.', copied: 'Copied to the clipboard. The brief has not been sent.', copyFallback: 'Automatic copying was unavailable. The text is selected; use your system copy command.', notProvided: 'Not provided', briefTitle: 'Collaboration brief', briefName: 'Name', briefOrganization: 'Organization / team', briefArea: 'Collaboration area', briefProblem: 'Problem and goal', briefSuffix: 'This brief was generated in your browser and has not been sent.'
  },
};

export const uiChinese: typeof uiEnglish = {
  nav: { home: '首页', projects: '项目', research: '研究', about: '关于我们', collaborate: '开始合作', contact: '合作联系', menu: '菜单', navigation: '主导航', language: '选择语言', currentLanguage: '选择语言，当前：{language}', homeLabel: 'Astrmira 幻梦星芒 首页' },
  footer: { motto: '以研究为起点，向可能性延伸。', back: '回到顶部', star: '幻梦星芒' },
  motion: { replay: '重播星芒', replayLabel: '重播星芒移动与文字凝聚', pause: '静止动效', enable: '启用动效', reduced: '已减少动态', scroll: '下滑探索' },
  toc: { title: '本页目录', overview: '概览' },
  carousel: { label: '研究论文，可左右翻阅', note: '论文 · 发现 · 进展', browse: '左右翻阅', previous: '查看前面的论文', next: '查看后面的论文', separator: '；' },
  common: { openSource: '开源项目', license: '许可证', github: '在 GitHub 查看', documentation: '阅读使用文档', releases: '查看发布版本', discuss: '讨论应用与合作', readResearch: '阅读我们的研究', astronomicalRecord: '天文资料', astronomySource: '天文资料', lastingCuriosity: '求索不息', beginQuestion: '从一个问题，开启对话', newWindow: '在新窗口打开' },
  projects: { all: '全部项目', data: '数据系统', agents: '智能体', harness: 'Agent Harness', filter: '筛选项目', count: '{count} 项', countOne: '{count} 项' },
  research: { all: '全部论文', vectors: '向量检索', llms: '大模型量化', theory: '表示与理论', filter: '筛选论文', label: '研究论文', search: '搜索论文、作者或关键词…', empty: '没有找到匹配的论文，试试其他关键词或研究方向。', count: '{count} 篇论文', countOne: '{count} 篇论文', browseFields: '浏览研究方向', arxivLabel: '在 arXiv 阅读 {title}（新窗口）' },
  paper: { details: '论文信息', authors: '作者', submitted: '首次提交', revised: '最近修订', version: '公开版本', arxiv: 'arXiv 原文', pdf: '阅读版本 PDF', readCite: '阅读与引用', continue: '继续阅读论文原文。', original: '完整推导、实验设置和结果见论文原文。', versions: '摘要与版本记录', fullPdf: 'PDF 全文', related: '相关论文' },
  form: { name: '如何称呼你（可选）', namePlaceholder: '姓名', organization: '组织 / 团队（可选）', organizationPlaceholder: '高校、实验室或公司', area: '合作方向', areas: ['科研 / 高校联合研究', '数据库与检索系统', 'Agent 平台与场景探索', '其他值得讨论的问题'], problem: '你希望一起解决什么问题？ *', placeholder: '问题背景、现有基础，以及希望达到的目标…', submit: '生成合作简报', note: '生成后可复制或下载。内容不会自动发送。', result: '你的合作简报', copy: '复制文本', download: '保存为 .txt', generated: '简报已在本地生成，尚未发送。', copied: '已复制到剪贴板。简报仍未发送。', copyFallback: '浏览器未允许自动复制。已选中文本，请使用系统复制命令。', notProvided: '未填写', briefTitle: '合作简报', briefName: '称呼', briefOrganization: '组织 / 团队', briefArea: '合作方向', briefProblem: '问题与目标', briefSuffix: '此简报在当前浏览器中生成，尚未发送。' },
};
